#! /usr/bin/env python3

import argparse
import os


def output(input):
    out = []
    if 'bs' in input:
        out.append( str(input['bs']) )

    out.append(input['file'])
    return ' '.join(out)


# Collect arguments
ap = argparse.ArgumentParser(
    prog='ccwc',
    description='DIY wc')
ap.add_argument('filename')
ap.add_argument('-c', '--bytes', action='store_true')

args = ap.parse_args()

# Figure out what to count
out = {'file': args.filename}
if args.bytes:
    out['bs'] = os.path.getsize(args.filename)

# Format and print the output
print(output(out))