#! /usr/bin/env python3

import argparse
import os


def do_count_bytes(filename):
    return os.path.getsize(filename)


def do_count(filename, action=all):
    res = {}
    
    with open(filename) as f:
        lines = f.readlines()

        if action == 'lines':
            res['lines'] = len(lines)

        if action == 'words':
            words = [len(line.split()) for line in lines]
            res['words'] = sum(words)

    return res


def output(input):
    out = []
    for o in ['bytes', 'lines', 'words']:
        if o in input:
            out.append( str(input[o]) )

    out.append(input['file'])
    return ' '.join(out)


# Collect arguments
ap = argparse.ArgumentParser(
    prog='ccwc',
    description='DIY wc')
ap.add_argument('filename')
ap.add_argument('-c', '--bytes', action='store_true')
ap.add_argument('-l', '--lines', action='store_true')
ap.add_argument('-w', '--words', action='store_true')


args = ap.parse_args()

# Figure out what to count
out = {'file': args.filename}


if args.bytes:
    out['bytes'] = do_count_bytes(args.filename)
elif args.lines:
    out['lines'] = do_count(args.filename, action='lines')['lines']
elif args.words:
    out['words'] = do_count(args.filename, action='words')['words']


# Format and print the output
print(output(out))